USE aero_blood;

INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('1', '3', 'Orthopedics', 'DM', 31);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('2', '9', 'Pediatrics', 'MS', 7);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('3', '13', 'Neurology', 'MS', 21);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('4', '25', 'Surgery', 'MS', 25);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('5', '26', 'Neurology', 'MBBS', 5);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('6', '29', 'Orthopedics', 'MD', 17);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('7', '31', 'General Medicine', 'MS', 24);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('8', '33', 'Pulmonology', 'MBBS', 12);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('9', '48', 'Pulmonology', 'MBBS', 1);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('10', '51', 'Pediatrics', 'MS', 6);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('11', '57', 'General Medicine', 'MS', 25);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('12', '61', 'Pulmonology', 'MS', 26);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('13', '70', 'General Medicine', 'MS', 31);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('14', '73', 'Cardiology', 'MD', 13);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('15', '74', 'General Medicine', 'DM', 22);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('16', '75', 'Pulmonology', 'MS', 29);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('17', '77', 'Nephrology', 'MBBS', 34);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('18', '82', 'ICU', 'MD', 4);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('19', '92', 'ICU', 'DM', 3);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('20', '96', 'Pulmonology', 'DM', 10);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('21', '107', 'Neurology', 'MS', 24);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('22', '110', 'Orthopedics', 'DM', 21);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('23', '117', 'Surgery', 'MS', 1);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('24', '120', 'Orthopedics', 'MS', 19);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('25', '128', 'Surgery', 'DM', 18);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('26', '145', 'Nephrology', 'MBBS', 21);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('27', '151', 'Orthopedics', 'MBBS', 11);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('28', '152', 'Pulmonology', 'MS', 1);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('29', '157', 'General Medicine', 'DM', 31);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('30', '165', 'Cardiology', 'DM', 21);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('31', '166', 'Pediatrics', 'MBBS', 10);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('32', '171', 'Orthopedics', 'DM', 5);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('33', '176', 'ICU', 'DM', 28);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('34', '184', 'Cardiology', 'DM', 11);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('35', '185', 'Neurology', 'MS', 14);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('36', '187', 'ICU', 'MD', 3);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('37', '189', 'General Medicine', 'MBBS', 8);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('38', '193', 'ICU', 'MD', 19);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('39', '197', 'General Medicine', 'MBBS', 14);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('40', '204', 'Neurology', 'MD', 35);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('41', '206', 'Pulmonology', 'DM', 35);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('42', '207', 'Cardiology', 'DM', 28);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('43', '212', 'ICU', 'MS', 18);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('44', '213', 'ICU', 'MD', 14);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('45', '219', 'General Medicine', 'MD', 15);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('46', '225', 'Pediatrics', 'MBBS', 5);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('47', '227', 'Cardiology', 'DM', 9);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('48', '228', 'Orthopedics', 'DM', 23);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('49', '232', 'Neurology', 'MS', 22);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('50', '233', 'Neurology', 'DM', 14);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('51', '244', 'Nephrology', 'DM', 3);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('52', '249', 'Orthopedics', 'DM', 3);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('53', '250', 'General Medicine', 'MBBS', 23);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('54', '253', 'Orthopedics', 'MBBS', 14);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('55', '255', 'Neurology', 'DM', 4);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('56', '262', 'Neurology', 'MBBS', 10);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('57', '265', 'ICU', 'MBBS', 2);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('58', '283', 'Nephrology', 'DM', 31);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('59', '291', 'Surgery', 'MD', 25);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('60', '301', 'Pulmonology', 'MD', 32);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('61', '319', 'Cardiology', 'MBBS', 13);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('62', '321', 'Cardiology', 'MS', 16);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('63', '327', 'Nephrology', 'MS', 32);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('64', '337', 'Pediatrics', 'MBBS', 29);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('65', '346', 'Surgery', 'DM', 2);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('66', '356', 'Nephrology', 'DM', 30);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('67', '359', 'Cardiology', 'MS', 31);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('68', '360', 'Neurology', 'MS', 28);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('69', '362', 'Cardiology', 'MD', 28);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('70', '364', 'Neurology', 'MBBS', 23);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('71', '368', 'Neurology', 'MBBS', 10);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('72', '372', 'Pulmonology', 'MS', 8);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('73', '379', 'Nephrology', 'DM', 3);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('74', '381', 'Pediatrics', 'MD', 1);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('75', '387', 'General Medicine', 'MS', 24);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('76', '393', 'Nephrology', 'MBBS', 3);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('77', '396', 'Cardiology', 'DM', 27);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('78', '397', 'ICU', 'DM', 26);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('79', '398', 'Pulmonology', 'MS', 33);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('80', '407', 'General Medicine', 'MBBS', 31);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('81', '409', 'Surgery', 'MS', 26);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('82', '413', 'Orthopedics', 'DM', 8);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('83', '422', 'Pediatrics', 'MS', 2);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('84', '425', 'Pediatrics', 'MBBS', 15);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('85', '428', 'Cardiology', 'DM', 19);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('86', '436', 'ICU', 'MS', 35);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('87', '449', 'Pediatrics', 'DM', 15);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('88', '455', 'General Medicine', 'MS', 7);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('89', '468', 'ICU', 'MBBS', 23);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('90', '472', 'ICU', 'MBBS', 22);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('91', '473', 'Pulmonology', 'DM', 12);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('92', '484', 'Neurology', 'MBBS', 15);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('93', '486', 'Pediatrics', 'MD', 31);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('94', '488', 'Neurology', 'DM', 34);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('95', '493', 'Cardiology', 'DM', 25);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('96', '494', 'Orthopedics', 'MBBS', 6);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('97', '497', 'General Medicine', 'MBBS', 17);
INSERT INTO doctor_source (doctor_id, employee_id, specialization, qualification, experience_years) VALUES ('98', '498', 'Nephrology', 'DM', 7);
