/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BloodbankRouteImport } from './routes/bloodbank'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAllocationsRouteImport } from './routes/admin.allocations'
import { Route as AdminBloodbanksRouteImport } from './routes/admin.bloodbanks'
import { Route as AdminDonorIntelligenceRouteImport } from './routes/admin.donor-intelligence'
import { Route as AdminEmergencyRouteImport } from './routes/admin.emergency'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminHospitalsRouteImport } from './routes/admin.hospitals'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminRedistributionNetworkRouteImport } from './routes/admin.redistribution-network'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminShortageNetworkRouteImport } from './routes/admin.shortage-network'
import { Route as AdminTransfersRouteImport } from './routes/admin.transfers'
import { Route as BloodbankIndexRouteImport } from './routes/bloodbank.index'
import { Route as BloodbankAllocationPreviewRouteImport } from './routes/bloodbank.allocation-preview'
import { Route as BloodbankBloodGroupsRouteImport } from './routes/bloodbank.blood-groups'
import { Route as BloodbankCompatibilityRouteImport } from './routes/bloodbank.compatibility'
import { Route as BloodbankDonationsRouteImport } from './routes/bloodbank.donations'
import { Route as BloodbankDonorIntelligenceRouteImport } from './routes/bloodbank.donor-intelligence'
import { Route as BloodbankDonorsRouteImport } from './routes/bloodbank.donors'
import { Route as BloodbankExpiryRouteImport } from './routes/bloodbank.expiry'
import { Route as BloodbankInventoryRouteImport } from './routes/bloodbank.inventory'
import { Route as BloodbankProfileRouteImport } from './routes/bloodbank.profile'
import { Route as BloodbankQuarantineRouteImport } from './routes/bloodbank.quarantine'
import { Route as BloodbankRedistributionRouteImport } from './routes/bloodbank.redistribution'
import { Route as BloodbankRequestsRouteImport } from './routes/bloodbank.requests'
import { Route as BloodbankShortageSurplusRouteImport } from './routes/bloodbank.shortage-surplus'
import { Route as BloodbankTransfersRouteImport } from './routes/bloodbank.transfers'
import { Route as HospitalIndexRouteImport } from './routes/hospital.index'
import { Route as HospitalAllocationIntelligenceRouteImport } from './routes/hospital.allocation-intelligence'
import { Route as HospitalEmergencyRouteImport } from './routes/hospital.emergency'
import { Route as HospitalHistoryRouteImport } from './routes/hospital.history'
import { Route as HospitalNewRequestRouteImport } from './routes/hospital.new-request'
import { Route as HospitalProfileRouteImport } from './routes/hospital.profile'
import { Route as HospitalRequestsRouteImport } from './routes/hospital.requests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BloodbankRoute = BloodbankRouteImport.update({
  id: '/bloodbank',
  path: '/bloodbank',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAllocationsRoute = AdminAllocationsRouteImport.update({
  id: '/allocations',
  path: '/allocations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBloodbanksRoute = AdminBloodbanksRouteImport.update({
  id: '/bloodbanks',
  path: '/bloodbanks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonorIntelligenceRoute = AdminDonorIntelligenceRouteImport.update({
  id: '/donor-intelligence',
  path: '/donor-intelligence',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmergencyRoute = AdminEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHospitalsRoute = AdminHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedistributionNetworkRoute =
  AdminRedistributionNetworkRouteImport.update({
    id: '/redistribution-network',
    path: '/redistribution-network',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShortageNetworkRoute = AdminShortageNetworkRouteImport.update({
  id: '/shortage-network',
  path: '/shortage-network',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransfersRoute = AdminTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AdminRoute,
} as any)
const BloodbankIndexRoute = BloodbankIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BloodbankRoute,
} as any)
const BloodbankAllocationPreviewRoute =
  BloodbankAllocationPreviewRouteImport.update({
    id: '/allocation-preview',
    path: '/allocation-preview',
    getParentRoute: () => BloodbankRoute,
  } as any)
const BloodbankBloodGroupsRoute = BloodbankBloodGroupsRouteImport.update({
  id: '/blood-groups',
  path: '/blood-groups',
  getParentRoute: () => BloodbankRoute,
} as any)
const BloodbankCompatibilityRoute = BloodbankCompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => BloodbankRoute,
} as any)
const BloodbankDonationsRoute = BloodbankDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => BloodbankRoute,
} as any)
const BloodbankDonorIntelligenceRoute =
  BloodbankDonorIntelligenceRouteImport.update({
    id: '/donor-intelligence',
    path: '/donor-intelligence',
    getParentRoute: () => BloodbankRoute,
  } as any)
const BloodbankDonorsRoute = BloodbankDonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => BloodbankRoute,
} as any)
const BloodbankExpiryRoute = BloodbankExpiryRouteImport.update({
  id: '/expiry',
  path: '/expiry',
  getParentRoute: () => BloodbankRoute,
} as any)
const BloodbankInventoryRoute = BloodbankInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => BloodbankRoute,
} as any)
const BloodbankProfileRoute = BloodbankProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BloodbankRoute,
} as any)
const BloodbankQuarantineRoute = BloodbankQuarantineRouteImport.update({
  id: '/quarantine',
  path: '/quarantine',
  getParentRoute: () => BloodbankRoute,
} as any)
const BloodbankRedistributionRoute = BloodbankRedistributionRouteImport.update({
  id: '/redistribution',
  path: '/redistribution',
  getParentRoute: () => BloodbankRoute,
} as any)
const BloodbankRequestsRoute = BloodbankRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => BloodbankRoute,
} as any)
const BloodbankShortageSurplusRoute =
  BloodbankShortageSurplusRouteImport.update({
    id: '/shortage-surplus',
    path: '/shortage-surplus',
    getParentRoute: () => BloodbankRoute,
  } as any)
const BloodbankTransfersRoute = BloodbankTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => BloodbankRoute,
} as any)
const HospitalIndexRoute = HospitalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalAllocationIntelligenceRoute =
  HospitalAllocationIntelligenceRouteImport.update({
    id: '/allocation-intelligence',
    path: '/allocation-intelligence',
    getParentRoute: () => HospitalRoute,
  } as any)
const HospitalEmergencyRoute = HospitalEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalHistoryRoute = HospitalHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalNewRequestRoute = HospitalNewRequestRouteImport.update({
  id: '/new-request',
  path: '/new-request',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalProfileRoute = HospitalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalRequestsRoute = HospitalRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => HospitalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bloodbank': typeof BloodbankRouteWithChildren
  '/hospital': typeof HospitalRouteWithChildren
  '/admin/allocations': typeof AdminAllocationsRoute
  '/admin/bloodbanks': typeof AdminBloodbanksRoute
  '/admin/donor-intelligence': typeof AdminDonorIntelligenceRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/redistribution-network': typeof AdminRedistributionNetworkRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/shortage-network': typeof AdminShortageNetworkRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/bloodbank/allocation-preview': typeof BloodbankAllocationPreviewRoute
  '/bloodbank/blood-groups': typeof BloodbankBloodGroupsRoute
  '/bloodbank/compatibility': typeof BloodbankCompatibilityRoute
  '/bloodbank/donations': typeof BloodbankDonationsRoute
  '/bloodbank/donor-intelligence': typeof BloodbankDonorIntelligenceRoute
  '/bloodbank/donors': typeof BloodbankDonorsRoute
  '/bloodbank/expiry': typeof BloodbankExpiryRoute
  '/bloodbank/inventory': typeof BloodbankInventoryRoute
  '/bloodbank/profile': typeof BloodbankProfileRoute
  '/bloodbank/quarantine': typeof BloodbankQuarantineRoute
  '/bloodbank/redistribution': typeof BloodbankRedistributionRoute
  '/bloodbank/requests': typeof BloodbankRequestsRoute
  '/bloodbank/shortage-surplus': typeof BloodbankShortageSurplusRoute
  '/bloodbank/transfers': typeof BloodbankTransfersRoute
  '/hospital/allocation-intelligence': typeof HospitalAllocationIntelligenceRoute
  '/hospital/emergency': typeof HospitalEmergencyRoute
  '/hospital/history': typeof HospitalHistoryRoute
  '/hospital/new-request': typeof HospitalNewRequestRoute
  '/hospital/profile': typeof HospitalProfileRoute
  '/hospital/requests': typeof HospitalRequestsRoute
  '/admin/': typeof AdminIndexRoute
  '/bloodbank/': typeof BloodbankIndexRoute
  '/hospital/': typeof HospitalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/allocations': typeof AdminAllocationsRoute
  '/admin/bloodbanks': typeof AdminBloodbanksRoute
  '/admin/donor-intelligence': typeof AdminDonorIntelligenceRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/redistribution-network': typeof AdminRedistributionNetworkRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/shortage-network': typeof AdminShortageNetworkRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/bloodbank/allocation-preview': typeof BloodbankAllocationPreviewRoute
  '/bloodbank/blood-groups': typeof BloodbankBloodGroupsRoute
  '/bloodbank/compatibility': typeof BloodbankCompatibilityRoute
  '/bloodbank/donations': typeof BloodbankDonationsRoute
  '/bloodbank/donor-intelligence': typeof BloodbankDonorIntelligenceRoute
  '/bloodbank/donors': typeof BloodbankDonorsRoute
  '/bloodbank/expiry': typeof BloodbankExpiryRoute
  '/bloodbank/inventory': typeof BloodbankInventoryRoute
  '/bloodbank/profile': typeof BloodbankProfileRoute
  '/bloodbank/quarantine': typeof BloodbankQuarantineRoute
  '/bloodbank/redistribution': typeof BloodbankRedistributionRoute
  '/bloodbank/requests': typeof BloodbankRequestsRoute
  '/bloodbank/shortage-surplus': typeof BloodbankShortageSurplusRoute
  '/bloodbank/transfers': typeof BloodbankTransfersRoute
  '/hospital/allocation-intelligence': typeof HospitalAllocationIntelligenceRoute
  '/hospital/emergency': typeof HospitalEmergencyRoute
  '/hospital/history': typeof HospitalHistoryRoute
  '/hospital/new-request': typeof HospitalNewRequestRoute
  '/hospital/profile': typeof HospitalProfileRoute
  '/hospital/requests': typeof HospitalRequestsRoute
  '/admin': typeof AdminIndexRoute
  '/bloodbank': typeof BloodbankIndexRoute
  '/hospital': typeof HospitalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bloodbank': typeof BloodbankRouteWithChildren
  '/hospital': typeof HospitalRouteWithChildren
  '/admin/allocations': typeof AdminAllocationsRoute
  '/admin/bloodbanks': typeof AdminBloodbanksRoute
  '/admin/donor-intelligence': typeof AdminDonorIntelligenceRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/redistribution-network': typeof AdminRedistributionNetworkRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/shortage-network': typeof AdminShortageNetworkRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/bloodbank/allocation-preview': typeof BloodbankAllocationPreviewRoute
  '/bloodbank/blood-groups': typeof BloodbankBloodGroupsRoute
  '/bloodbank/compatibility': typeof BloodbankCompatibilityRoute
  '/bloodbank/donations': typeof BloodbankDonationsRoute
  '/bloodbank/donor-intelligence': typeof BloodbankDonorIntelligenceRoute
  '/bloodbank/donors': typeof BloodbankDonorsRoute
  '/bloodbank/expiry': typeof BloodbankExpiryRoute
  '/bloodbank/inventory': typeof BloodbankInventoryRoute
  '/bloodbank/profile': typeof BloodbankProfileRoute
  '/bloodbank/quarantine': typeof BloodbankQuarantineRoute
  '/bloodbank/redistribution': typeof BloodbankRedistributionRoute
  '/bloodbank/requests': typeof BloodbankRequestsRoute
  '/bloodbank/shortage-surplus': typeof BloodbankShortageSurplusRoute
  '/bloodbank/transfers': typeof BloodbankTransfersRoute
  '/hospital/allocation-intelligence': typeof HospitalAllocationIntelligenceRoute
  '/hospital/emergency': typeof HospitalEmergencyRoute
  '/hospital/history': typeof HospitalHistoryRoute
  '/hospital/new-request': typeof HospitalNewRequestRoute
  '/hospital/profile': typeof HospitalProfileRoute
  '/hospital/requests': typeof HospitalRequestsRoute
  '/admin/': typeof AdminIndexRoute
  '/bloodbank/': typeof BloodbankIndexRoute
  '/hospital/': typeof HospitalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bloodbank'
    | '/hospital'
    | '/admin/allocations'
    | '/admin/bloodbanks'
    | '/admin/donor-intelligence'
    | '/admin/emergency'
    | '/admin/health'
    | '/admin/hospitals'
    | '/admin/inventory'
    | '/admin/redistribution-network'
    | '/admin/requests'
    | '/admin/shortage-network'
    | '/admin/transfers'
    | '/bloodbank/allocation-preview'
    | '/bloodbank/blood-groups'
    | '/bloodbank/compatibility'
    | '/bloodbank/donations'
    | '/bloodbank/donor-intelligence'
    | '/bloodbank/donors'
    | '/bloodbank/expiry'
    | '/bloodbank/inventory'
    | '/bloodbank/profile'
    | '/bloodbank/quarantine'
    | '/bloodbank/redistribution'
    | '/bloodbank/requests'
    | '/bloodbank/shortage-surplus'
    | '/bloodbank/transfers'
    | '/hospital/allocation-intelligence'
    | '/hospital/emergency'
    | '/hospital/history'
    | '/hospital/new-request'
    | '/hospital/profile'
    | '/hospital/requests'
    | '/admin/'
    | '/bloodbank/'
    | '/hospital/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/allocations'
    | '/admin/bloodbanks'
    | '/admin/donor-intelligence'
    | '/admin/emergency'
    | '/admin/health'
    | '/admin/hospitals'
    | '/admin/inventory'
    | '/admin/redistribution-network'
    | '/admin/requests'
    | '/admin/shortage-network'
    | '/admin/transfers'
    | '/bloodbank/allocation-preview'
    | '/bloodbank/blood-groups'
    | '/bloodbank/compatibility'
    | '/bloodbank/donations'
    | '/bloodbank/donor-intelligence'
    | '/bloodbank/donors'
    | '/bloodbank/expiry'
    | '/bloodbank/inventory'
    | '/bloodbank/profile'
    | '/bloodbank/quarantine'
    | '/bloodbank/redistribution'
    | '/bloodbank/requests'
    | '/bloodbank/shortage-surplus'
    | '/bloodbank/transfers'
    | '/hospital/allocation-intelligence'
    | '/hospital/emergency'
    | '/hospital/history'
    | '/hospital/new-request'
    | '/hospital/profile'
    | '/hospital/requests'
    | '/admin'
    | '/bloodbank'
    | '/hospital'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bloodbank'
    | '/hospital'
    | '/admin/allocations'
    | '/admin/bloodbanks'
    | '/admin/donor-intelligence'
    | '/admin/emergency'
    | '/admin/health'
    | '/admin/hospitals'
    | '/admin/inventory'
    | '/admin/redistribution-network'
    | '/admin/requests'
    | '/admin/shortage-network'
    | '/admin/transfers'
    | '/bloodbank/allocation-preview'
    | '/bloodbank/blood-groups'
    | '/bloodbank/compatibility'
    | '/bloodbank/donations'
    | '/bloodbank/donor-intelligence'
    | '/bloodbank/donors'
    | '/bloodbank/expiry'
    | '/bloodbank/inventory'
    | '/bloodbank/profile'
    | '/bloodbank/quarantine'
    | '/bloodbank/redistribution'
    | '/bloodbank/requests'
    | '/bloodbank/shortage-surplus'
    | '/bloodbank/transfers'
    | '/hospital/allocation-intelligence'
    | '/hospital/emergency'
    | '/hospital/history'
    | '/hospital/new-request'
    | '/hospital/profile'
    | '/hospital/requests'
    | '/admin/'
    | '/bloodbank/'
    | '/hospital/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BloodbankRoute: typeof BloodbankRouteWithChildren
  HospitalRoute: typeof HospitalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloodbank': {
      id: '/bloodbank'
      path: '/bloodbank'
      fullPath: '/bloodbank'
      preLoaderRoute: typeof BloodbankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/allocations': {
      id: '/admin/allocations'
      path: '/allocations'
      fullPath: '/admin/allocations'
      preLoaderRoute: typeof AdminAllocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bloodbanks': {
      id: '/admin/bloodbanks'
      path: '/bloodbanks'
      fullPath: '/admin/bloodbanks'
      preLoaderRoute: typeof AdminBloodbanksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donor-intelligence': {
      id: '/admin/donor-intelligence'
      path: '/donor-intelligence'
      fullPath: '/admin/donor-intelligence'
      preLoaderRoute: typeof AdminDonorIntelligenceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emergency': {
      id: '/admin/emergency'
      path: '/emergency'
      fullPath: '/admin/emergency'
      preLoaderRoute: typeof AdminEmergencyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hospitals': {
      id: '/admin/hospitals'
      path: '/hospitals'
      fullPath: '/admin/hospitals'
      preLoaderRoute: typeof AdminHospitalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redistribution-network': {
      id: '/admin/redistribution-network'
      path: '/redistribution-network'
      fullPath: '/admin/redistribution-network'
      preLoaderRoute: typeof AdminRedistributionNetworkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shortage-network': {
      id: '/admin/shortage-network'
      path: '/shortage-network'
      fullPath: '/admin/shortage-network'
      preLoaderRoute: typeof AdminShortageNetworkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transfers': {
      id: '/admin/transfers'
      path: '/transfers'
      fullPath: '/admin/transfers'
      preLoaderRoute: typeof AdminTransfersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bloodbank/': {
      id: '/bloodbank/'
      path: '/'
      fullPath: '/bloodbank/'
      preLoaderRoute: typeof BloodbankIndexRouteImport
      parentRoute: typeof BloodbankRoute
    }
    '/bloodbank/allocation-preview': {
      id: '/bloodbank/allocation-preview'
      path: '/allocation-preview'
      fullPath: '/bloodbank/allocation-preview'
      preLoaderRoute: typeof BloodbankAllocationPreviewRouteImport
      parentRoute: typeof BloodbankRoute
    }
    '/bloodbank/blood-groups': {
      id: '/bloodbank/blood-groups'
      path: '/blood-groups'
      fullPath: '/bloodbank/blood-groups'
      preLoaderRoute: typeof BloodbankBloodGroupsRouteImport
      parentRoute: typeof BloodbankRoute
    }
    '/bloodbank/compatibility': {
      id: '/bloodbank/compatibility'
      path: '/compatibility'
      fullPath: '/bloodbank/compatibility'
      preLoaderRoute: typeof BloodbankCompatibilityRouteImport
      parentRoute: typeof BloodbankRoute
    }
    '/bloodbank/donations': {
      id: '/bloodbank/donations'
      path: '/donations'
      fullPath: '/bloodbank/donations'
      preLoaderRoute: typeof BloodbankDonationsRouteImport
      parentRoute: typeof BloodbankRoute
    }
    '/bloodbank/donor-intelligence': {
      id: '/bloodbank/donor-intelligence'
      path: '/donor-intelligence'
      fullPath: '/bloodbank/donor-intelligence'
      preLoaderRoute: typeof BloodbankDonorIntelligenceRouteImport
      parentRoute: typeof BloodbankRoute
    }
    '/bloodbank/donors': {
      id: '/bloodbank/donors'
      path: '/donors'
      fullPath: '/bloodbank/donors'
      preLoaderRoute: typeof BloodbankDonorsRouteImport
      parentRoute: typeof BloodbankRoute
    }
    '/bloodbank/expiry': {
      id: '/bloodbank/expiry'
      path: '/expiry'
      fullPath: '/bloodbank/expiry'
      preLoaderRoute: typeof BloodbankExpiryRouteImport
      parentRoute: typeof BloodbankRoute
    }
    '/bloodbank/inventory': {
      id: '/bloodbank/inventory'
      path: '/inventory'
      fullPath: '/bloodbank/inventory'
      preLoaderRoute: typeof BloodbankInventoryRouteImport
      parentRoute: typeof BloodbankRoute
    }
    '/bloodbank/profile': {
      id: '/bloodbank/profile'
      path: '/profile'
      fullPath: '/bloodbank/profile'
      preLoaderRoute: typeof BloodbankProfileRouteImport
      parentRoute: typeof BloodbankRoute
    }
    '/bloodbank/quarantine': {
      id: '/bloodbank/quarantine'
      path: '/quarantine'
      fullPath: '/bloodbank/quarantine'
      preLoaderRoute: typeof BloodbankQuarantineRouteImport
      parentRoute: typeof BloodbankRoute
    }
    '/bloodbank/redistribution': {
      id: '/bloodbank/redistribution'
      path: '/redistribution'
      fullPath: '/bloodbank/redistribution'
      preLoaderRoute: typeof BloodbankRedistributionRouteImport
      parentRoute: typeof BloodbankRoute
    }
    '/bloodbank/requests': {
      id: '/bloodbank/requests'
      path: '/requests'
      fullPath: '/bloodbank/requests'
      preLoaderRoute: typeof BloodbankRequestsRouteImport
      parentRoute: typeof BloodbankRoute
    }
    '/bloodbank/shortage-surplus': {
      id: '/bloodbank/shortage-surplus'
      path: '/shortage-surplus'
      fullPath: '/bloodbank/shortage-surplus'
      preLoaderRoute: typeof BloodbankShortageSurplusRouteImport
      parentRoute: typeof BloodbankRoute
    }
    '/bloodbank/transfers': {
      id: '/bloodbank/transfers'
      path: '/transfers'
      fullPath: '/bloodbank/transfers'
      preLoaderRoute: typeof BloodbankTransfersRouteImport
      parentRoute: typeof BloodbankRoute
    }
    '/hospital/': {
      id: '/hospital/'
      path: '/'
      fullPath: '/hospital/'
      preLoaderRoute: typeof HospitalIndexRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/allocation-intelligence': {
      id: '/hospital/allocation-intelligence'
      path: '/allocation-intelligence'
      fullPath: '/hospital/allocation-intelligence'
      preLoaderRoute: typeof HospitalAllocationIntelligenceRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/emergency': {
      id: '/hospital/emergency'
      path: '/emergency'
      fullPath: '/hospital/emergency'
      preLoaderRoute: typeof HospitalEmergencyRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/history': {
      id: '/hospital/history'
      path: '/history'
      fullPath: '/hospital/history'
      preLoaderRoute: typeof HospitalHistoryRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/new-request': {
      id: '/hospital/new-request'
      path: '/new-request'
      fullPath: '/hospital/new-request'
      preLoaderRoute: typeof HospitalNewRequestRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/profile': {
      id: '/hospital/profile'
      path: '/profile'
      fullPath: '/hospital/profile'
      preLoaderRoute: typeof HospitalProfileRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/requests': {
      id: '/hospital/requests'
      path: '/requests'
      fullPath: '/hospital/requests'
      preLoaderRoute: typeof HospitalRequestsRouteImport
      parentRoute: typeof HospitalRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAllocationsRoute: typeof AdminAllocationsRoute
  AdminBloodbanksRoute: typeof AdminBloodbanksRoute
  AdminDonorIntelligenceRoute: typeof AdminDonorIntelligenceRoute
  AdminEmergencyRoute: typeof AdminEmergencyRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminHospitalsRoute: typeof AdminHospitalsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminRedistributionNetworkRoute: typeof AdminRedistributionNetworkRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminShortageNetworkRoute: typeof AdminShortageNetworkRoute
  AdminTransfersRoute: typeof AdminTransfersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAllocationsRoute: AdminAllocationsRoute,
  AdminBloodbanksRoute: AdminBloodbanksRoute,
  AdminDonorIntelligenceRoute: AdminDonorIntelligenceRoute,
  AdminEmergencyRoute: AdminEmergencyRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminHospitalsRoute: AdminHospitalsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminRedistributionNetworkRoute: AdminRedistributionNetworkRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminShortageNetworkRoute: AdminShortageNetworkRoute,
  AdminTransfersRoute: AdminTransfersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BloodbankRouteChildren {
  BloodbankAllocationPreviewRoute: typeof BloodbankAllocationPreviewRoute
  BloodbankBloodGroupsRoute: typeof BloodbankBloodGroupsRoute
  BloodbankCompatibilityRoute: typeof BloodbankCompatibilityRoute
  BloodbankDonationsRoute: typeof BloodbankDonationsRoute
  BloodbankDonorIntelligenceRoute: typeof BloodbankDonorIntelligenceRoute
  BloodbankDonorsRoute: typeof BloodbankDonorsRoute
  BloodbankExpiryRoute: typeof BloodbankExpiryRoute
  BloodbankInventoryRoute: typeof BloodbankInventoryRoute
  BloodbankProfileRoute: typeof BloodbankProfileRoute
  BloodbankQuarantineRoute: typeof BloodbankQuarantineRoute
  BloodbankRedistributionRoute: typeof BloodbankRedistributionRoute
  BloodbankRequestsRoute: typeof BloodbankRequestsRoute
  BloodbankShortageSurplusRoute: typeof BloodbankShortageSurplusRoute
  BloodbankTransfersRoute: typeof BloodbankTransfersRoute
  BloodbankIndexRoute: typeof BloodbankIndexRoute
}

const BloodbankRouteChildren: BloodbankRouteChildren = {
  BloodbankAllocationPreviewRoute: BloodbankAllocationPreviewRoute,
  BloodbankBloodGroupsRoute: BloodbankBloodGroupsRoute,
  BloodbankCompatibilityRoute: BloodbankCompatibilityRoute,
  BloodbankDonationsRoute: BloodbankDonationsRoute,
  BloodbankDonorIntelligenceRoute: BloodbankDonorIntelligenceRoute,
  BloodbankDonorsRoute: BloodbankDonorsRoute,
  BloodbankExpiryRoute: BloodbankExpiryRoute,
  BloodbankInventoryRoute: BloodbankInventoryRoute,
  BloodbankProfileRoute: BloodbankProfileRoute,
  BloodbankQuarantineRoute: BloodbankQuarantineRoute,
  BloodbankRedistributionRoute: BloodbankRedistributionRoute,
  BloodbankRequestsRoute: BloodbankRequestsRoute,
  BloodbankShortageSurplusRoute: BloodbankShortageSurplusRoute,
  BloodbankTransfersRoute: BloodbankTransfersRoute,
  BloodbankIndexRoute: BloodbankIndexRoute,
}

const BloodbankRouteWithChildren = BloodbankRoute._addFileChildren(
  BloodbankRouteChildren,
)

interface HospitalRouteChildren {
  HospitalAllocationIntelligenceRoute: typeof HospitalAllocationIntelligenceRoute
  HospitalEmergencyRoute: typeof HospitalEmergencyRoute
  HospitalHistoryRoute: typeof HospitalHistoryRoute
  HospitalNewRequestRoute: typeof HospitalNewRequestRoute
  HospitalProfileRoute: typeof HospitalProfileRoute
  HospitalRequestsRoute: typeof HospitalRequestsRoute
  HospitalIndexRoute: typeof HospitalIndexRoute
}

const HospitalRouteChildren: HospitalRouteChildren = {
  HospitalAllocationIntelligenceRoute: HospitalAllocationIntelligenceRoute,
  HospitalEmergencyRoute: HospitalEmergencyRoute,
  HospitalHistoryRoute: HospitalHistoryRoute,
  HospitalNewRequestRoute: HospitalNewRequestRoute,
  HospitalProfileRoute: HospitalProfileRoute,
  HospitalRequestsRoute: HospitalRequestsRoute,
  HospitalIndexRoute: HospitalIndexRoute,
}

const HospitalRouteWithChildren = HospitalRoute._addFileChildren(
  HospitalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BloodbankRoute: BloodbankRouteWithChildren,
  HospitalRoute: HospitalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
